// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobufClasses;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string country = 1;</code>
   */
  String getCountry();
  /**
   * <code>string country = 1;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>string city = 2;</code>
   */
  String getCity();
  /**
   * <code>string city = 2;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string zip = 3;</code>
   */
  String getZip();
  /**
   * <code>string zip = 3;</code>
   */
  com.google.protobuf.ByteString
      getZipBytes();

  /**
   * <code>string street = 4;</code>
   */
  String getStreet();
  /**
   * <code>string street = 4;</code>
   */
  com.google.protobuf.ByteString
      getStreetBytes();
}
