// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobufClasses;

/**
 * Protobuf type {@code Announcement}
 */
public  final class Announcement extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Announcement)
        AnnouncementOrBuilder {
  // Use Announcement.newBuilder() to construct.
  private Announcement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Announcement() {
    petOwnerUsername_ = "";
    description_ = "";
    dateOfCreation_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Announcement(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            petOwnerUsername_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 26: {
            TimeInterval.Builder subBuilder = null;
            if (timeInterval_ != null) {
              subBuilder = timeInterval_.toBuilder();
            }
            timeInterval_ = input.readMessage(TimeInterval.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timeInterval_);
              timeInterval_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            Pet.Builder subBuilder = null;
            if (pet_ != null) {
              subBuilder = pet_.toBuilder();
            }
            pet_ = input.readMessage(Pet.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pet_);
              pet_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            Address.Builder subBuilder = null;
            if (address_ != null) {
              subBuilder = address_.toBuilder();
            }
            address_ = input.readMessage(Address.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(address_);
              address_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            dateOfCreation_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Protobuf.internal_static_Announcement_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Protobuf.internal_static_Announcement_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Announcement.class, Announcement.Builder.class);
  }

  public static final int PETOWNERUSERNAME_FIELD_NUMBER = 1;
  private volatile Object petOwnerUsername_;
  /**
   * <code>string petOwnerUsername = 1;</code>
   */
  public String getPetOwnerUsername() {
    Object ref = petOwnerUsername_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      petOwnerUsername_ = s;
      return s;
    }
  }
  /**
   * <code>string petOwnerUsername = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPetOwnerUsernameBytes() {
    Object ref = petOwnerUsername_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      petOwnerUsername_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  private volatile Object description_;
  /**
   * <code>string description = 2;</code>
   */
  public String getDescription() {
    Object ref = description_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    Object ref = description_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEINTERVAL_FIELD_NUMBER = 3;
  private TimeInterval timeInterval_;
  /**
   * <code>.TimeInterval timeInterval = 3;</code>
   */
  public boolean hasTimeInterval() {
    return timeInterval_ != null;
  }
  /**
   * <code>.TimeInterval timeInterval = 3;</code>
   */
  public TimeInterval getTimeInterval() {
    return timeInterval_ == null ? TimeInterval.getDefaultInstance() : timeInterval_;
  }
  /**
   * <code>.TimeInterval timeInterval = 3;</code>
   */
  public TimeIntervalOrBuilder getTimeIntervalOrBuilder() {
    return getTimeInterval();
  }

  public static final int PET_FIELD_NUMBER = 4;
  private Pet pet_;
  /**
   * <code>.Pet pet = 4;</code>
   */
  public boolean hasPet() {
    return pet_ != null;
  }
  /**
   * <code>.Pet pet = 4;</code>
   */
  public Pet getPet() {
    return pet_ == null ? Pet.getDefaultInstance() : pet_;
  }
  /**
   * <code>.Pet pet = 4;</code>
   */
  public PetOrBuilder getPetOrBuilder() {
    return getPet();
  }

  public static final int ADDRESS_FIELD_NUMBER = 5;
  private Address address_;
  /**
   * <code>.Address address = 5;</code>
   */
  public boolean hasAddress() {
    return address_ != null;
  }
  /**
   * <code>.Address address = 5;</code>
   */
  public Address getAddress() {
    return address_ == null ? Address.getDefaultInstance() : address_;
  }
  /**
   * <code>.Address address = 5;</code>
   */
  public AddressOrBuilder getAddressOrBuilder() {
    return getAddress();
  }

  public static final int DATEOFCREATION_FIELD_NUMBER = 6;
  private volatile Object dateOfCreation_;
  /**
   * <code>string dateOfCreation = 6;</code>
   */
  public String getDateOfCreation() {
    Object ref = dateOfCreation_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dateOfCreation_ = s;
      return s;
    }
  }
  /**
   * <code>string dateOfCreation = 6;</code>
   */
  public com.google.protobuf.ByteString
      getDateOfCreationBytes() {
    Object ref = dateOfCreation_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dateOfCreation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPetOwnerUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, petOwnerUsername_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
    }
    if (timeInterval_ != null) {
      output.writeMessage(3, getTimeInterval());
    }
    if (pet_ != null) {
      output.writeMessage(4, getPet());
    }
    if (address_ != null) {
      output.writeMessage(5, getAddress());
    }
    if (!getDateOfCreationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, dateOfCreation_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPetOwnerUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, petOwnerUsername_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
    }
    if (timeInterval_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTimeInterval());
    }
    if (pet_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getPet());
    }
    if (address_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getAddress());
    }
    if (!getDateOfCreationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, dateOfCreation_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Announcement)) {
      return super.equals(obj);
    }
    Announcement other = (Announcement) obj;

    boolean result = true;
    result = result && getPetOwnerUsername()
        .equals(other.getPetOwnerUsername());
    result = result && getDescription()
        .equals(other.getDescription());
    result = result && (hasTimeInterval() == other.hasTimeInterval());
    if (hasTimeInterval()) {
      result = result && getTimeInterval()
          .equals(other.getTimeInterval());
    }
    result = result && (hasPet() == other.hasPet());
    if (hasPet()) {
      result = result && getPet()
          .equals(other.getPet());
    }
    result = result && (hasAddress() == other.hasAddress());
    if (hasAddress()) {
      result = result && getAddress()
          .equals(other.getAddress());
    }
    result = result && getDateOfCreation()
        .equals(other.getDateOfCreation());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PETOWNERUSERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPetOwnerUsername().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    if (hasTimeInterval()) {
      hash = (37 * hash) + TIMEINTERVAL_FIELD_NUMBER;
      hash = (53 * hash) + getTimeInterval().hashCode();
    }
    if (hasPet()) {
      hash = (37 * hash) + PET_FIELD_NUMBER;
      hash = (53 * hash) + getPet().hashCode();
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    hash = (37 * hash) + DATEOFCREATION_FIELD_NUMBER;
    hash = (53 * hash) + getDateOfCreation().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Announcement parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Announcement parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Announcement parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Announcement parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Announcement parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Announcement parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Announcement parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Announcement parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Announcement parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Announcement parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Announcement parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Announcement parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Announcement prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Announcement}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Announcement)
          AnnouncementOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protobuf.internal_static_Announcement_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protobuf.internal_static_Announcement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Announcement.class, Announcement.Builder.class);
    }

    // Construct using origin.protobuf.Announcement.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      petOwnerUsername_ = "";

      description_ = "";

      if (timeIntervalBuilder_ == null) {
        timeInterval_ = null;
      } else {
        timeInterval_ = null;
        timeIntervalBuilder_ = null;
      }
      if (petBuilder_ == null) {
        pet_ = null;
      } else {
        pet_ = null;
        petBuilder_ = null;
      }
      if (addressBuilder_ == null) {
        address_ = null;
      } else {
        address_ = null;
        addressBuilder_ = null;
      }
      dateOfCreation_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Protobuf.internal_static_Announcement_descriptor;
    }

    public Announcement getDefaultInstanceForType() {
      return Announcement.getDefaultInstance();
    }

    public Announcement build() {
      Announcement result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public Announcement buildPartial() {
      Announcement result = new Announcement(this);
      result.petOwnerUsername_ = petOwnerUsername_;
      result.description_ = description_;
      if (timeIntervalBuilder_ == null) {
        result.timeInterval_ = timeInterval_;
      } else {
        result.timeInterval_ = timeIntervalBuilder_.build();
      }
      if (petBuilder_ == null) {
        result.pet_ = pet_;
      } else {
        result.pet_ = petBuilder_.build();
      }
      if (addressBuilder_ == null) {
        result.address_ = address_;
      } else {
        result.address_ = addressBuilder_.build();
      }
      result.dateOfCreation_ = dateOfCreation_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Announcement) {
        return mergeFrom((Announcement)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Announcement other) {
      if (other == Announcement.getDefaultInstance()) return this;
      if (!other.getPetOwnerUsername().isEmpty()) {
        petOwnerUsername_ = other.petOwnerUsername_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (other.hasTimeInterval()) {
        mergeTimeInterval(other.getTimeInterval());
      }
      if (other.hasPet()) {
        mergePet(other.getPet());
      }
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (!other.getDateOfCreation().isEmpty()) {
        dateOfCreation_ = other.dateOfCreation_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Announcement parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Announcement) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object petOwnerUsername_ = "";
    /**
     * <code>string petOwnerUsername = 1;</code>
     */
    public String getPetOwnerUsername() {
      Object ref = petOwnerUsername_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        petOwnerUsername_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string petOwnerUsername = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPetOwnerUsernameBytes() {
      Object ref = petOwnerUsername_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        petOwnerUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string petOwnerUsername = 1;</code>
     */
    public Builder setPetOwnerUsername(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      petOwnerUsername_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string petOwnerUsername = 1;</code>
     */
    public Builder clearPetOwnerUsername() {
      
      petOwnerUsername_ = getDefaultInstance().getPetOwnerUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string petOwnerUsername = 1;</code>
     */
    public Builder setPetOwnerUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      petOwnerUsername_ = value;
      onChanged();
      return this;
    }

    private Object description_ = "";
    /**
     * <code>string description = 2;</code>
     */
    public String getDescription() {
      Object ref = description_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     */
    public Builder setDescription(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private TimeInterval timeInterval_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            TimeInterval, TimeInterval.Builder, TimeIntervalOrBuilder> timeIntervalBuilder_;
    /**
     * <code>.TimeInterval timeInterval = 3;</code>
     */
    public boolean hasTimeInterval() {
      return timeIntervalBuilder_ != null || timeInterval_ != null;
    }
    /**
     * <code>.TimeInterval timeInterval = 3;</code>
     */
    public TimeInterval getTimeInterval() {
      if (timeIntervalBuilder_ == null) {
        return timeInterval_ == null ? TimeInterval.getDefaultInstance() : timeInterval_;
      } else {
        return timeIntervalBuilder_.getMessage();
      }
    }
    /**
     * <code>.TimeInterval timeInterval = 3;</code>
     */
    public Builder setTimeInterval(TimeInterval value) {
      if (timeIntervalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timeInterval_ = value;
        onChanged();
      } else {
        timeIntervalBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.TimeInterval timeInterval = 3;</code>
     */
    public Builder setTimeInterval(
        TimeInterval.Builder builderForValue) {
      if (timeIntervalBuilder_ == null) {
        timeInterval_ = builderForValue.build();
        onChanged();
      } else {
        timeIntervalBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.TimeInterval timeInterval = 3;</code>
     */
    public Builder mergeTimeInterval(TimeInterval value) {
      if (timeIntervalBuilder_ == null) {
        if (timeInterval_ != null) {
          timeInterval_ =
            TimeInterval.newBuilder(timeInterval_).mergeFrom(value).buildPartial();
        } else {
          timeInterval_ = value;
        }
        onChanged();
      } else {
        timeIntervalBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.TimeInterval timeInterval = 3;</code>
     */
    public Builder clearTimeInterval() {
      if (timeIntervalBuilder_ == null) {
        timeInterval_ = null;
        onChanged();
      } else {
        timeInterval_ = null;
        timeIntervalBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.TimeInterval timeInterval = 3;</code>
     */
    public TimeInterval.Builder getTimeIntervalBuilder() {
      
      onChanged();
      return getTimeIntervalFieldBuilder().getBuilder();
    }
    /**
     * <code>.TimeInterval timeInterval = 3;</code>
     */
    public TimeIntervalOrBuilder getTimeIntervalOrBuilder() {
      if (timeIntervalBuilder_ != null) {
        return timeIntervalBuilder_.getMessageOrBuilder();
      } else {
        return timeInterval_ == null ?
            TimeInterval.getDefaultInstance() : timeInterval_;
      }
    }
    /**
     * <code>.TimeInterval timeInterval = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            TimeInterval, TimeInterval.Builder, TimeIntervalOrBuilder>
        getTimeIntervalFieldBuilder() {
      if (timeIntervalBuilder_ == null) {
        timeIntervalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                TimeInterval, TimeInterval.Builder, TimeIntervalOrBuilder>(
                getTimeInterval(),
                getParentForChildren(),
                isClean());
        timeInterval_ = null;
      }
      return timeIntervalBuilder_;
    }

    private Pet pet_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            Pet, Pet.Builder, PetOrBuilder> petBuilder_;
    /**
     * <code>.Pet pet = 4;</code>
     */
    public boolean hasPet() {
      return petBuilder_ != null || pet_ != null;
    }
    /**
     * <code>.Pet pet = 4;</code>
     */
    public Pet getPet() {
      if (petBuilder_ == null) {
        return pet_ == null ? Pet.getDefaultInstance() : pet_;
      } else {
        return petBuilder_.getMessage();
      }
    }
    /**
     * <code>.Pet pet = 4;</code>
     */
    public Builder setPet(Pet value) {
      if (petBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pet_ = value;
        onChanged();
      } else {
        petBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Pet pet = 4;</code>
     */
    public Builder setPet(
        Pet.Builder builderForValue) {
      if (petBuilder_ == null) {
        pet_ = builderForValue.build();
        onChanged();
      } else {
        petBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Pet pet = 4;</code>
     */
    public Builder mergePet(Pet value) {
      if (petBuilder_ == null) {
        if (pet_ != null) {
          pet_ =
            Pet.newBuilder(pet_).mergeFrom(value).buildPartial();
        } else {
          pet_ = value;
        }
        onChanged();
      } else {
        petBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Pet pet = 4;</code>
     */
    public Builder clearPet() {
      if (petBuilder_ == null) {
        pet_ = null;
        onChanged();
      } else {
        pet_ = null;
        petBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Pet pet = 4;</code>
     */
    public Pet.Builder getPetBuilder() {
      
      onChanged();
      return getPetFieldBuilder().getBuilder();
    }
    /**
     * <code>.Pet pet = 4;</code>
     */
    public PetOrBuilder getPetOrBuilder() {
      if (petBuilder_ != null) {
        return petBuilder_.getMessageOrBuilder();
      } else {
        return pet_ == null ?
            Pet.getDefaultInstance() : pet_;
      }
    }
    /**
     * <code>.Pet pet = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            Pet, Pet.Builder, PetOrBuilder>
        getPetFieldBuilder() {
      if (petBuilder_ == null) {
        petBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                Pet, Pet.Builder, PetOrBuilder>(
                getPet(),
                getParentForChildren(),
                isClean());
        pet_ = null;
      }
      return petBuilder_;
    }

    private Address address_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            Address, Address.Builder, AddressOrBuilder> addressBuilder_;
    /**
     * <code>.Address address = 5;</code>
     */
    public boolean hasAddress() {
      return addressBuilder_ != null || address_ != null;
    }
    /**
     * <code>.Address address = 5;</code>
     */
    public Address getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? Address.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <code>.Address address = 5;</code>
     */
    public Builder setAddress(Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
        onChanged();
      } else {
        addressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Address address = 5;</code>
     */
    public Builder setAddress(
        Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
        onChanged();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Address address = 5;</code>
     */
    public Builder mergeAddress(Address value) {
      if (addressBuilder_ == null) {
        if (address_ != null) {
          address_ =
            Address.newBuilder(address_).mergeFrom(value).buildPartial();
        } else {
          address_ = value;
        }
        onChanged();
      } else {
        addressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Address address = 5;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = null;
        onChanged();
      } else {
        address_ = null;
        addressBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Address address = 5;</code>
     */
    public Address.Builder getAddressBuilder() {
      
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.Address address = 5;</code>
     */
    public AddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            Address.getDefaultInstance() : address_;
      }
    }
    /**
     * <code>.Address address = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            Address, Address.Builder, AddressOrBuilder>
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                Address, Address.Builder, AddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private Object dateOfCreation_ = "";
    /**
     * <code>string dateOfCreation = 6;</code>
     */
    public String getDateOfCreation() {
      Object ref = dateOfCreation_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dateOfCreation_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string dateOfCreation = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDateOfCreationBytes() {
      Object ref = dateOfCreation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dateOfCreation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dateOfCreation = 6;</code>
     */
    public Builder setDateOfCreation(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dateOfCreation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dateOfCreation = 6;</code>
     */
    public Builder clearDateOfCreation() {
      
      dateOfCreation_ = getDefaultInstance().getDateOfCreation();
      onChanged();
      return this;
    }
    /**
     * <code>string dateOfCreation = 6;</code>
     */
    public Builder setDateOfCreationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dateOfCreation_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Announcement)
  }

  // @@protoc_insertion_point(class_scope:Announcement)
  private static final Announcement DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Announcement();
  }

  public static Announcement getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Announcement>
      PARSER = new com.google.protobuf.AbstractParser<Announcement>() {
    public Announcement parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Announcement(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Announcement> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Announcement> getParserForType() {
    return PARSER;
  }

  public Announcement getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

