// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobufClasses;

public interface PetOwnerInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PetOwnerInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string f_name = 2;</code>
   */
  String getFName();
  /**
   * <code>string f_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getFNameBytes();

  /**
   * <code>string l_name = 3;</code>
   */
  String getLName();
  /**
   * <code>string l_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getLNameBytes();

  /**
   * <code>string phone = 4;</code>
   */
  String getPhone();
  /**
   * <code>string phone = 4;</code>
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string email = 5;</code>
   */
  String getEmail();
  /**
   * <code>string email = 5;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
