// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package origin.protobufClasses;

public interface PetOwnerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PetOwner)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   */
  String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string f_name = 3;</code>
   */
  String getFName();
  /**
   * <code>string f_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getFNameBytes();

  /**
   * <code>string l_name = 4;</code>
   */
  String getLName();
  /**
   * <code>string l_name = 4;</code>
   */
  com.google.protobuf.ByteString
      getLNameBytes();

  /**
   * <code>int32 age = 5;</code>
   */
  int getAge();

  /**
   * <code>string phone = 6;</code>
   */
  String getPhone();
  /**
   * <code>string phone = 6;</code>
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string email = 7;</code>
   */
  String getEmail();
  /**
   * <code>string email = 7;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
